### ISSUE TITLE
How to prepare instruction-tuning dataset?

### ISSUE THREAD

**Issue by CoolColoury** [Hannibal046/xRAG#12]
I noticed that the composition of the datasets in the `prepare_dataset.ipynb` file is different: some datasets have `background` field and some do not.

At the same time, I found that `background` is a required field in `encode_with_chat_format_finetune` when  instruction-tuning.

I would like to ask how you deal with it specifically, thanks!

**Comment by Hannibal046** [comment]
Hi, for the datasets without natural context,  we conduct retrieval and fetch the top-1 doc as the context.
![image](https://github.com/user-attachments/assets/3e2d0cc9-8da3-4234-8010-b2408cb534f8)

**Comment by Xnhyacinth** [comment]
Hi, @Hannibal046 How long did it take to perform this retrieval on all the training data?

**Comment by daehoon-lg** [comment]
Hi @Hannibal046 , could the dataset that contains the top-1 doc as a background be published as well?
