### ISSUE TITLE
Is RetrieverTokenizer missing? 

### ISSUE THREAD

**Issue by gordonhu608** [Hannibal046/xRAG#2]
As titled. Do we need to train retriever? 
`tokenizer = RetrieverTokenizer.from_pretrained(args.base_model,additional_special_tokens=["[Q]","[D]"])`

**Comment by Hannibal046** [comment]
Hi, in xRAG you could either train your own retriever or using existing one.

 In `src/language_modeling/` we use the existing retriever: https://huggingface.co/Salesforce/SFR-Embedding-Mistral

Code in `src/dense_retrieval` is from my other project: https://github.com/Hannibal046/nanoDPR, where you can train your own retriever.
