### ISSUE TITLE
求train和eval用的数据

### ISSUE THREAD

**Issue by zhaotl4** [Hannibal046/xRAG#5]
作者您好！xrag这篇工作非常惊艳，我们在复现它的结果，请问下能否提供处理好的训练和测试用的数据？非常感谢！

**Comment by Hannibal046** [comment]
你好,感谢对我们工作的关注! 实验所需要的train and eval data 都是公开的,我们也提供了相应的链接和处理方法在README中,请问有碰到什么问题吗? 我们目前也在训练xRAG-v2, 用到了一些合成数据, 我们会在下一个版本进行更新.

**Comment by zhaotl4** [comment]
感谢作者回复！我们在处理数据时，使用代码对每个query生成对应的top-1文档的流程不是非常确定，想和作者您再确认下。使用的是src/dense_retrival中的相关代码，我们的流程如下:

1.doc2embedding 对wiki 的corpus生成emb
2.bulid_index 根据生成的emb建立索引
3.colbert_server 启动server，替换index name和root为上一步建立的索引
4.colbert_retrieval 生成最终的top1文件

请问是否是这样的流程？如果不对，能否辛苦作者提供一个shell脚本？

**Comment by zhaotl4** [comment]
作者您好！在执行doc2embedding.py时， from model import ColBERT会报错，请问是否忘记上次model.py文件？

**Comment by Hannibal046** [comment]
你好,`src/dense_retrival`里面是我自己复现的DPR和ColBERT的代码,你可以直接用[官方ColBERT](https://github.com/stanford-futuredata/ColBERT)的代码和checkpoint来构建index, 我们在实验中也是用的ColBERT repo中的代码.

**Comment by zhaotl4** [comment]
作者你好，我们使用了ColBERT repo 中的代码来构建index，和数据集进行了测试。但是效果和论文中相比差距较大，所以有几个点想和作者您确认下我们的setting是否正确，希望您能回复，非常感谢！

1.使用enwiki-dec2021/text-list-100-sec.jsonl 作为语料库，3317w条数据
2. 用 [ColBERT repo代码](https://github.com/stanford-futuredata/ColBERT/blob/main/docs/intro2new.ipynb) 构建index时，设置 kmeans_niters=4

```

with Run().context(RunConfig(nranks=1, experiment='notebook')):  # nranks specifies the number of GPUs to use
    config = ColBERTConfig(doc_maxlen=doc_maxlen, nbits=nbits, kmeans_niters=4)                                                    
    indexer = Indexer(checkpoint=checkpoint, config=config)
    indexer.index(name=index_name, collection=collection, overwrite=False)

```

**Comment by Hannibal046** [comment]
你好:
- enwiki的数据我们也包括了infobox,但我觉得这个应该不会有那么大的影响
- colbert的代码修改自:
![image](https://github.com/Hannibal046/xRAG/assets/38466901/b0d5e7ce-af1a-4566-a632-6f1bb1158d98)
同时,我们也上传了triviaqa的数据集和检索结果,你可以对比下检索结果来验证来检索的正确性.

请问你说的"效果和论文中相比差距较大"指的是什么呢?你们用的命令是什么呢?

**Comment by zhaotl4** [comment]
作者你好，感谢回复！
我们测试在nq数据集中的结果如下，我们测试结果/论文结果，
![20240624112634](https://github.com/Hannibal046/xRAG/assets/55618390/60683d4e-6325-4e03-bf9c-999a57f486f9)

使用的命令:

```
CUDA_VISIBLE_DEVICES=0 python -m src.eval.run_eval \
        --data nq_open \
        --model_name_or_path Hannibal046/xrag-7b \
        --retriever_name_or_path pretrain_models/SFR-Embedding-Mistral \
        --use_rag

```

对于语料的问题，想确认下是将infobox和text-list-100-sec合并后作为的语料库吗？
对于构建索引，我们的方法看起来有些参数和你们不同，我们再尝试下

**Comment by Hannibal046** [comment]
"对于语料的问题，想确认下是将infobox和text-list-100-sec合并后作为的语料库吗" -- 是的
这个看起来应该是检索的问题,同时也没有差距很大呀, 35.68/39.34 = 0.90, 39.10/42.71 = 0.91

**Comment by Hannibal046** [comment]
也不用局限于ColbertV2, 只是我比较熟悉这个模型而已. 任何dense retrieval模型都适用, 甚至你可以直接用`SFR-Embedding-Mistral`构建索引,效果应该会更好

**Comment by zhaotl4** [comment]
> 你好:
> 
> * enwiki的数据我们也包括了infobox,但我觉得这个应该不会有那么大的影响
> * colbert的代码修改自:
>   ![image](https://private-user-images.githubusercontent.com/38466901/342190778-b0d5e7ce-af1a-4566-a632-6f1bb1158d98.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzMDE2NjcsIm5iZiI6MTcxOTMwMTM2NywicGF0aCI6Ii8zODQ2NjkwMS8zNDIxOTA3NzgtYjBkNWU3Y2UtYWYxYS00NTY2LWE2MzItNmYxYmIxMTU4ZDk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDA3NDI0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhYTM0NzRjNGQ1ZWRjMGEzZDM4ZjJjYjQ0ZWM0ZGQ3ZDc0NzEyOWQ2OTRiZjJhY2RiNDQ3M2E0M2ZmMzNmNmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5dY9b_P-pPGnUbIXBVLTWYXE5GqI0dRsPO7XEUK1d0o)
>   同时,我们也上传了triviaqa的数据集和检索结果,你可以对比下检索结果来验证来检索的正确性.
> 
> 请问你说的"效果和论文中相比差距较大"指的是什么呢?你们用的命令是什么呢?

作者你好，请问下你们按照图中的方式，kmeans_niters=20，对于整个语料库是否存在超时问题？

```
[E ProcessGroupNCCL.cpp:461] To avoid data inconsistency, we are taking the entire process down.
terminate called after throwing an instance of 'std::runtime_error'
  what():  [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=5, OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1806216 milliseconds before timing out.
```

**Comment by Hannibal046** [comment]
Hi, 我当时没有碰到类似的报错. 但是看样子应该是数据集太大,预处理时间超过NCCL的默认timeout(1800000).

**Comment by peterwan1** [comment]
@Hannibal046 请问triviaqa的数据集和检索结果在哪里呀，只看到了triviaqa的test数据集
