### ISSUE TITLE
Topk performance (k>1)

### ISSUE THREAD

**Issue by Lu-kuan-lpk** [Hannibal046/xRAG#6]
Thanks for the great work! As the paper fix the parameter of retrieved chunks to 1, I wonder does the performance still good if the num of documents retrieved is large than 1, which is more similar to the real world RAG situation. Does some performance score has been test?

**Comment by Hannibal046** [comment]
Hi, thanks for asking! We acknowledge this limitation for currect xRAG-v1 as stated in our paper:

> We only consider the Top-1 retrieval setting, while ensembling multiple relevant documents has been shown to be effective for RAG systems due to the complementary information contained in Top-K documents. We believe there is potential advantage for xRAG to scale to multi-document settings, as the input length of xRAG for multi-documents scales by a factor of 1, while for RAG, it scales by the document length factor.

We do conduct some preliminary experiments and found out that enlarging K doesn't bring significant improvement for current xRAG as it brings to vanilla RAG. For some datasets, it even hurts the performance. One plausible reason is that during the training process of xRAG, it has never been exposed to multi-document setting so maybe we could mitigate this from the construction of our datasets.



BTW, we are working on the next version of xRAG, and we aim to extend top1 to topk (hopefully). Stay tuned!

**Comment by Lu-kuan-lpk** [comment]
Thanks for the fast response!
